package NGO.UI;

import NGO.User;

public class GeneralWindow extends javax.swing.JFrame {

	User user;

	public GeneralWindow(User user) {
		this.user = user;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMinaProj = new javax.swing.JButton();
        btnAllaProj = new javax.swing.JButton();
        btnGlobalGoals = new javax.swing.JButton();
        btnUppgifter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Välkommen du");

        btnMinaProj.setText("Mina projekt");
        btnMinaProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaProjActionPerformed(evt);
            }
        });

        btnAllaProj.setText("Alla Projekt");

        btnGlobalGoals.setText("Hållbarhetsmål");

        btnUppgifter.setText("Mina Uppgifter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnMinaProj)
                        .addGap(62, 62, 62)
                        .addComponent(btnAllaProj)
                        .addGap(102, 102, 102)
                        .addComponent(btnGlobalGoals)
                        .addGap(81, 81, 81)
                        .addComponent(btnUppgifter)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinaProj)
                    .addComponent(btnAllaProj)
                    .addComponent(btnGlobalGoals)
                    .addComponent(btnUppgifter))
                .addContainerGap(364, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinaProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaProjActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_btnMinaProjActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllaProj;
    private javax.swing.JButton btnGlobalGoals;
    private javax.swing.JButton btnMinaProj;
    private javax.swing.JButton btnUppgifter;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
