/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NGO.UI;
import NGO.User;

/**
 *
 * @author david
 */
public class GenWin extends javax.swing.JPanel {

    /**
     * Creates new form B
     */
    User user;
    public GenWin(User user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMinaProj = new javax.swing.JButton();
        btnAllaProj = new javax.swing.JButton();
        btnGlobalGoals = new javax.swing.JButton();
        btnUppgifter = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        btnMinaProj.setText("Mina projekt");

        btnAllaProj.setText("Alla projekt");

        btnGlobalGoals.setText("Hållbarhetsmål");

        btnUppgifter.setText("Mina uppgifter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(btnMinaProj)
                .addGap(38, 38, 38)
                .addComponent(btnAllaProj)
                .addGap(41, 41, 41)
                .addComponent(btnGlobalGoals)
                .addGap(51, 51, 51)
                .addComponent(btnUppgifter)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinaProj)
                    .addComponent(btnAllaProj)
                    .addComponent(btnGlobalGoals)
                    .addComponent(btnUppgifter))
                .addContainerGap(372, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllaProj;
    private javax.swing.JButton btnGlobalGoals;
    private javax.swing.JButton btnMinaProj;
    private javax.swing.JButton btnUppgifter;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
